name: test core

on:
  pull_request:
    paths:
      - '.github/workflows/test-core.yml'
      - 'cli/**'
      - 'tauri/**'
      - 'tauri-api/**'
      - 'tauri-utils/**'

env:
  RUST_BACKTRACE: 1

jobs:
  build-tauri-core:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: build
        run: |
          cd ./tauri
          cargo build
        env:
          TAURI_DIST_DIR: ${{ runner.workspace }}/tauri/tauri/examples/communication/dist
          TAURI_DIR: ${{ runner.workspace }}/tauri/tauri/examples/communication/src-tauri
      - name: test
        run: |
          cargo test
        env:
          TAURI_DIST_DIR: ${{ runner.workspace }}/tauri/tauri/examples/communication/dist
          TAURI_DIR: ${{ runner.workspace }}/tauri/tauri/examples/communication/src-tauri

  test-tauri-cli:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, i686-pc-windows-gnu, x86_64-apple-darwin]

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }}

  test-tauri-js-cli:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: cargo install --path ./cli/tauri-bundler --force
      - name: test
        timeout-minutes: 15
        run: |
          cd ./cli/tauri.js
          yarn
          yarn test
